name: HACS

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Validate HACS dashboard repository
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa # main
        with:
          category: plugin
          comment: false
